version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: ./src/Api/Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8081:8081"
    env_file:
      - ../src/Api/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recordsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
